### ISSUE TITLE
Crash on version 0.6.5 or git master when running without root

### ISSUE THREAD

**Issue by azuwis** [berghetti/netproc#15]
On current git master 42bbb7ba48732759ecba36503460c8936b17e77a

```
$ ./bin/netproc 
[DEBUG] src/sock.c:91 - Error create socket: Operation not permitted
[FATAL] Root is needed to running
AddressSanitizer:DEADLYSIGNAL
=================================================================
==174502==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x0000004074c4 bp 0x7fffffffb840 sp 0x7fffffffb810 T0)
==174502==The signal is caused by a READ memory access.
==174502==Hint: address points to the zero page.
    #0 0x4074c4 in hashtable_min_detroy src/hashtable.c:363
    #1 0x40552d in connection_free src/connection.c:301
    #2 0x40928f in main src/main.c:272
    #3 0x7ffff763dacd in __libc_start_call_main (/nix/store/905gkx2q1pswixwmi1qfhfl6mik3f22l-glibc-2.37-8/lib/libc.so.6+0x23acd)
    #4 0x7ffff763db88 in __libc_start_main_alias_2 (/nix/store/905gkx2q1pswixwmi1qfhfl6mik3f22l-glibc-2.37-8/lib/libc.so.6+0x23b88)
    #5 0x4037b4 in _start (/home/azuwis/src/netproc/bin/netproc+0x4037b4)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV src/hashtable.c:363 in hashtable_min_detroy
==174502==ABORTING
```

git bisect found 921eafaf8e50085c6bbcc9f06ae7b4f1ec4d943c is the first bad commit.

```
$ git bisect log
...
git bisect good 322e6e90ae309b6506081c5692356863d7b9ac6d
# bad: [921eafaf8e50085c6bbcc9f06ae7b4f1ec4d943c] checking
git bisect bad 921eafaf8e50085c6bbcc9f06ae7b4f1ec4d943c
# first bad commit: [921eafaf8e50085c6bbcc9f06ae7b4f1ec4d943c] checking
```

**Comment by berghetti** [comment]
**[FATAL] Root is needed to running**

**Comment by berghetti** [comment]
**[FATAL] Root is needed to running**

**Comment by azuwis** [comment]
I know netproc need root to run, but before commit https://github.com/berghetti/netproc/commit/921eafaf8e50085c6bbcc9f06ae7b4f1ec4d943c, it won't crash when running as normal user.

I was trying to bump netproc version for NixOS https://github.com/berghetti/netproc/commit/921eafaf8e50085c6bbcc9f06ae7b4f1ec4d943c, got a coredump, and found the changed behavior.

If it was not considered as a bug, I'll finish the version bump as it is.

**Comment by berghetti** [comment]
Ok.
New version,[ 0.6.6](https://github.com/berghetti/netproc/releases/tag/0.6.6), current master, fix it.

Thanks.
